const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.destroy,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Chao: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{DestruirForaDoLayout: 0},
	{Chaves: 0},
	{Direita: 0},
	{Esquerda: 0},
	{Pulo: 0},
	{Toque: 0},
	{Senóide: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PontaPlataformaEsquerdo: 0},
	{PontaPlataformadireita: 0},
	{Limite: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlacaFim: 0},
	{PlacaInicio: 0},
	{caixa: 0},
	{Partículas: 0},
	{Cogumelo: 0},
	{PontaPlataformadireita2: 0},
	{Estado: 0},
	{criaPremio: 0}
];

self.InstanceType = {
	Chao: class extends self.ITiledBackgroundInstance {},
	Chaves: class extends self.ISpriteInstance {},
	Direita: class extends self.ISpriteInstance {},
	Esquerda: class extends self.ISpriteInstance {},
	Pulo: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PontaPlataformaEsquerdo: class extends self.ISpriteInstance {},
	PontaPlataformadireita: class extends self.ISpriteInstance {},
	Limite: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlacaFim: class extends self.ISpriteInstance {},
	PlacaInicio: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Cogumelo: class extends self.ISpriteInstance {},
	PontaPlataformadireita2: class extends self.ISpriteInstance {}
}